### PR TITLE
US-023 Make Map Interactive

### PR DESCRIPTION
**Pull request by 0-Gixty-0**
Created dynamically placed map markers which appear only for highlighted areas on the map. Works for both region and municipality. Also added a button to show and hide markers since they can be quite numerous when looking at municipalities.

Popup for marker includes:
- Location name
- Number of events for selected type at location
- Latitude
- Longitude

Notes:

- Updated color scale to 9 colors since many locations could greatly exceed 6 events.
- It may appear as though the marker is not in the center of a tile. However, I have cross referenced a few of the coordinates returned from the centroid function and they mostly line up with google maps values within a value of 0.1 - 0.5 error. I believe this is unavoidable and I don't think it is worth it to find a different data source since the ones I looked at also had this margin of error. **Zooming into the tile usually places the marker more in the center of the tile**. Unfortunately some markers are just bad and end up on the edge of a tile. Limitation of the data imo. See example in image

image
image

Popup example:
image

### CODE REVIEW

**Review by DuchessMuhr — CHANGES_REQUESTED** [review]
I would like to know what it would take to actually make it so that the markers are actually on the region when more zoomed out. I believe that it is in a consumers interest to get an overview of all of Sweden when looking at regions and atm I don't think that it really looks that great. 
Screenshot from 2024-05-15 11-52-45

Even when looking at municipalities in a users surrounding region it is kind of rough to see what marker corresponds to what municipality.

image

**Comment by 0-Gixty-0** [comment]
I believe I have now fixed the issue from your requested changes @DuchessMuhr. I have locked the icon size to a certain value and I have also used iconAnchor to forcibly move the marker "tip" 15 pixels left and 30 pixels up. When selecting "Brand" as crime type almost all of the municipalities are highlighted and therefore most of the marker positions can be checked and there is substantial improvement from the previous version. Would like some input on the positioning of the markers before merge.

I am slightly worried that this may also be linked to individual browsers and window size. How does it look on your computers?

**This is the same location as in my original screenshot and the difference is quite clear**
image

**Comment by DuchessMuhr** [comment]
@0-Gixty-0 Are the changes for the legend and color dynamic, otherwise me and @jmarkusson have done that in our issue #61 if that may cause merge conflicts?

**Review by DuchessMuhr — APPROVED** [review]
LGTM! Nicely done.

**Comment by 0-Gixty-0** [comment]
> @0-Gixty-0 Are the changes for the legend and color dynamic, otherwise me and @jmarkusson have done that in our issue #61 if that may cause merge conflicts?

I did not realize that you guys modified the legend and coloring of the highlights. Yes it will cause a merge conflict down the line since we have modified the same function in two different ways. I will merge this change in now and then your merge should be done manually in order to keep your color functions

**Pull request merged**
